sudo: required
services:
  - docker

before_install:
  - docker build -t anilpatro044/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anilpatro044/react-test npm test

after_success:
  # Build individual images for each of the section
  - docker build -t anilpatro044/multi-client ./client
  - docker build -t anilpatro044/multi-nginx ./nginx
  - docker build -t anilpatro044/multi-server ./server
  - docker build -t anilpatro044/multi-worker ./worker

  # login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all those build images and push them off to docker hub
  - docker push anilpatro044/multi-client
  - docker push anilpatro044/multi-nginx
  - docker push anilpatro044/multi-server
  - docker push anilpatro044/multi-worker
